BSBookingQuery/Models/ErrorViewModel.cs
namespace BSBookingQuery.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BSBookingQuery/Controllers/HomeController.cs
using BSBookingQuery.Models;
using Domain.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Service;
using System.Diagnostics;

namespace BSBookingQuery.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private HotelService hotelService;
        public HomeController(ILogger<HomeController> logger, HotelService hotelService)
        {
            _logger = logger;
            this.hotelService = hotelService;
        }

        public IActionResult Index()
        {
            var data = hotelService.GetAll();
            return View(data);
        }
        [HttpPost]
        public IActionResult Index(string name=null,string location=null,int lowrating=0,int highrating=0)
        {
            var data = hotelService.GetAllBySearch(name,location,lowrating,highrating);
            return View(data);
        }
        public IActionResult HotelDetails(int id)
        {
            var data = hotelService.GetDetailsWithComment(id);

            if (data == null) return NotFound();

            return View(data);
        }
        [HttpPost]
        public IActionResult HotelDetails(HotelViewModel model)
        {
                       
            hotelService.CreateComment(model);
            return RedirectToAction("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BSBookingQuery/Controllers/HotelController.cs
using Domain.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Service;

namespace BSBookingQuery.Controllers
{
    public class HotelController : Controller
    {
        private HotelService hotelService;
        private IWebHostEnvironment _he;
        public HotelController(HotelService hotelService, IWebHostEnvironment he)
        {
            this.hotelService = hotelService;
            _he = he;
        }

        public IActionResult Index()
        {
            var data = hotelService.GetAll();

            if (data == null) return NotFound();
            return View(data);
        }
        public IActionResult Get()
        {
            var data = hotelService.GetAll();

            if (data == null) return NotFound();

            return Ok(data);
        }


        public IActionResult Details(int id)
        {
            var data = hotelService.GetById(id);

            if (data == null) return NotFound();

            return View(data);
        }

        public IActionResult Create()
        {
            ViewData["locationId"] = new SelectList(hotelService.LocationDropDown(), "Value", "Text");
            ViewData["ratingId"] = new SelectList(hotelService.RatingDropDown(), "Value", "Text");
            return View();
        }
        [HttpPost]
        public IActionResult Create(HotelViewModel model, IFormFile image)
        {
            //if (!ModelState.IsValid) return BadRequest(ModelState);
            if (image != null)
            {
                var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                image.CopyTo(new FileStream(name, FileMode.Create));
                model.Image = "Images/" + image.FileName;
            }
            if (image == null)
            {
                model.Image = "Images/noimage.png";
            }
            hotelService.Create(model);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var data = hotelService.GetById(id);
            ViewData["locationId"] = new SelectList(hotelService.LocationDropDown(), "Value", "Text");
            ViewData["ratingId"] = new SelectList(hotelService.RatingDropDown(), "Value", "Text");

            if (data == null) return NotFound();

            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(HotelViewModel model, IFormFile image)
        {
            if (image != null)
            {
                var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                image.CopyTo(new FileStream(name, FileMode.Create));
                model.Image = "Images/" + image.FileName;
            }
            if (image == null)
            {
                model.Image = "Images/noimage.png";
            }

            hotelService.Update(model);
            return RedirectToAction("Index");
        }
    }
}

BSBookingQuery/Controllers/LocationController.cs
using Domain.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Service;

namespace BSBookingQuery.Controllers
{
    public class LocationController : Controller
    {
       
        private LocationService locationService;
        public LocationController(LocationService locationService)
        {
            this.locationService = locationService;
        }

        public IActionResult Index()
        {
            var data = locationService.GetAll();

            if (data == null) return NotFound();
            return View(data);
        }
        public IActionResult Get()
        {
            var data = locationService.GetAll();

            if (data == null) return NotFound();

            return Ok(data);
        }

       
        public IActionResult Details(int id)
        {
            var data = locationService.GetById(id);

            if (data == null) return NotFound();

            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(LocationViewModel model)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

             locationService.Create(model);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var data = locationService.GetById(id);

            if (data == null) return NotFound();

            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(LocationViewModel model)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            locationService.Update(model);
            return RedirectToAction("Index");
        }
    }
}

BSBookingQuery/Controllers/RatingController.cs
using Domain.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Service;

namespace BSBookingQuery.Controllers
{
    public class RatingController : Controller
    {
        private RatingService ratingService;
        public RatingController(RatingService ratingService)
        {
            this.ratingService = ratingService;
        }

        public IActionResult Index()
        {
            var data = ratingService.GetAll();

            if (data == null) return NotFound();
            return View(data);
        }
        public IActionResult Get()
        {
            var data = ratingService.GetAll();

            if (data == null) return NotFound();

            return Ok(data);
        }


        public IActionResult Details(int id)
        {
            var data = ratingService.GetById(id);

            if (data == null) return NotFound();

            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(RatingViewModel model)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            ratingService.Create(model);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var data = ratingService.GetById(id);

            if (data == null) return NotFound();

            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(RatingViewModel model)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            ratingService.Update(model);
            return RedirectToAction("Index");
        }
    }
}

BSBookingQuery/Views/Home/HotelDetails.cshtml
@model Domain.ViewModel.HotelViewModel

@{
    ViewData["Title"] = "HotelDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />

<h2 class="text-info">Hotel Details</h2>
<form asp-action="HotelDetails" method="post" enctype="multipart/form-data">
    <div class="p-4 rounded border row">
        <input asp-for="Id" type="hidden" />
        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" readonly class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="HotelType"></label>
                </div>
                <div class="col-8">
                    <input asp-for="HotelType" readonly class="form-control" />
                </div>
                <span asp-validation-for="HotelType" class="text-danger"></span>
            </div>
           
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Price" readonly class="form-control" />
                </div>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

           
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="LocationNm"></label>
                </div>
                <div class="col-8">
                    <input asp-for="LocationNm" readonly class="form-control" />
                </div>
                <span asp-validation-for="LocationNm" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="RatingNm"></label>
                </div>
                <div class="col-8">
                    @*<select asp-for="ProductTypeId" asp-items="ViewBag.productTypeId" class="form-control"></select>*@
                    <input asp-for="RatingNm" readonly class="form-control" />
                </div>
                <span asp-validation-for="RatingNm" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Details"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Details" readonly class="form-control" />
                </div>
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>

            <div class="form-group row">
                <div class="col-4">
                   
                </div>
                <div class="col-8">
                    <h2 class="text-warning">Comments</h2>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="CommentorName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CommentorName" class="form-control" />
                    </div>
                    <span asp-validation-for="CommentorName" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Title"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Title" class="form-control" />
                    </div>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Comments"></label>
                    </div>
                    <div class="col-8">
                        
                        <textarea asp-for="Comments" type="text" class="form-control" rows="5" autofocus></textarea>
                    </div>
                    <span asp-validation-for="Comments" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group" style="text-align:end">
            <input type="submit" class="btn btn-primary" value="Post Comment" />
            
        </div>
                </div>

            </div>

            <div class="form-group">
                <a asp-action="Index" class="btn btn-success">Back to Home</a>
            </div>
        </div>
        <div class="col-1"></div>
        <div class="col-3">
            <img src="~/@Model.Image" width="100%" style="border-radius:5px;border:1px solid #efefef" />
            <br />
            <br />
            <br />
            <div class="row">
                <h3>Comments</h3>
                @foreach (var product in Model.commentLists)
                {
                    
                        <div class="card">
                            <div class="card-header" style="color:aqua">
                                <h4 class="font-weight-normal">
                                    <label style="font-size:23px;color:steelblue">Title :@product.Title</label>
                                </h4>
                            <div class="btn-group">
                                <label style="font-size:20px; color:#a51313"><b>Author : @product.CommentorName</b></label>
                            </div>
                            </div>

                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-center">
                                    
                                    <p>@product.Comments</p>
                                </div>
                            </div>
                        </div>
                    
                }


        </div>

           

        </div>
       

    </div>
</form>

BSBookingQuery/Views/Home/Index.cshtml
@model IEnumerable<Domain.ViewModel.HotelViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <div class="row">
        <div class="col-2">
            <input type="text" class="form-control" name="name" placeholder="Name" />
        </div>
        <div class="col-2">
            <input type="text" class="form-control" name="location" placeholder="Location" />
        </div>
        <div class="col-2">
            <input type="number" class="form-control" name="lowrating" placeholder="From Rating" />
         </div>
        <div class="col-2">
            <input type="number" class="form-control" name="highrating" placeholder="To Rating" />
        </div>
        
        <div class="col-2">
           
            <input type="submit" value="Search" class="btn btn-success" />
        </div>

        <div class="col-3"></div>
    </div>
</form>
<br />
<div class="row">
    @foreach (var product in Model)
    {
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="font-weight-normal">
                        <label style="font-size:23px;color:steelblue">@product.Name <span style="text-align:end">Rating: @product.RatingNm</span></label>
                    </h4>
                    <p>Type:@product.HotelType <span></span>Location: @product.LocationNm</p>
                </div>
                <img src="~/@product.Image" alt="Card Image" class="card-img-top" style="height:200px;" />
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size:20px; color:#a51313"><b>Price : @product.Price</b></label>
                        </div>
                        <a asp-action="HotelDetails" asp-Controller="Home" asp-route-id="@product.Id" class="btn btn-success pull-right">Details</a>
                    </div>
                </div>
            </div>
        </div>
    }
    <br />
    <br />
    

</div>
<div class="form-group">
    <a asp-action="Index" class="btn btn-success">Back to Home</a>
</div>

BSBookingQuery/Views/Hotel/Create.cshtml
@model Domain.ViewModel.HotelViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelType" class="control-label"></label>
                <input asp-for="HotelType" class="form-control" />
                <span asp-validation-for="HotelType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationNm" class="control-label"></label>
                @*<input asp-for="LocationId" class="form-control" />*@
                <select asp-for="LocationId" asp-items="ViewBag.locationId" class="form-control"></select>
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RatingId" class="control-label"></label>
                <select asp-for="RatingId" asp-items="ViewBag.ratingId" class="form-control"></select>
                @*<input asp-for="RatingId" class="form-control" />*@
                <span asp-validation-for="RatingId" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="NearestLoc1" class="control-label"></label>
                <input asp-for="NearestLoc1" class="form-control" />
                <span asp-validation-for="NearestLoc1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NearestLoc2" class="control-label"></label>
                <input asp-for="NearestLoc2" class="form-control" />
                <span asp-validation-for="NearestLoc2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" type="file"/>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BSBookingQuery/Views/Hotel/Edit.cshtml
@model Domain.ViewModel.HotelViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelType" class="control-label"></label>
                <input asp-for="HotelType" class="form-control" />
                <span asp-validation-for="HotelType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationNm" class="control-label"></label>
                @*<input asp-for="LocationId" class="form-control" />*@
                <select asp-for="LocationId" asp-items="ViewBag.locationId" class="form-control"></select>
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RatingId" class="control-label"></label>
                <select asp-for="RatingId" asp-items="ViewBag.ratingId" class="form-control"></select>
                @*<input asp-for="RatingId" class="form-control" />*@
                <span asp-validation-for="RatingId" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="NearestLoc1" class="control-label"></label>
                <input asp-for="NearestLoc1" class="form-control" />
                <span asp-validation-for="NearestLoc1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NearestLoc2" class="control-label"></label>
                <input asp-for="NearestLoc2" class="form-control" />
                <span asp-validation-for="NearestLoc2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger" type="file"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<div class="col-1"></div>
<div class="col-3">
    <img src="~/@Model.Image" width="100%" style="border-radius:5px;border:1px solid #efefef" />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BSBookingQuery/Views/Hotel/Index.cshtml
@model IEnumerable<Domain.ViewModel.HotelViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotelType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Details)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.LocationNm)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.RatingNm)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NearestLoc1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NearestLoc2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HotelType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.LocationNm)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.RatingNm)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NearestLoc1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NearestLoc2)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Image)*@
                    <img src="~/@item.Image" alt="Card Image" class="card-img-top" style="height:50px;" />
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id }) |
                @Html.ActionLink("Details", "Details", new {  id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

BSBookingQuery/Views/Location/Create.cshtml
@model Domain.ViewModel.LocationViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BSBookingQuery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BSBookingQuery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BSBookingQuery.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BSBookingQuery</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="Index">Location</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rating" asp-action="Index">Rating</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Index">Hotel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BSBookingQuery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>